name: Auto Update MLF Playlist

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install yt-dlp
        run: pip install yt-dlp

      - name: Generate playlist
        run: |
          URL1=$(yt-dlp -g "https://id.xhamster.com/videos/hijab-muslim-stepmom-get-fucked-hard-so-hot-and-creampie-in-hotel-room-xhPwFEX")

          echo "#EXTM3U" > mlf.m3u
          echo "" >> mlf.m3u

          echo "#EXTINF:-1 tvg-id=\"mlf1\" tvg-name=\"mlf1\" group-title=\"MLF\",mlf1" >> mlf.m3u
          echo "$URL1" >> mlf.m3u
