name: Auto Update MLF Playlist

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          pip install -U yt-dlp
          sudo apt-get update
          sudo apt-get install -y ffmpeg

      - name: Generate playlist
        run: |

          URL1=$(yt-dlp --impersonate chrome -g "https://id.xhamster.com/videos/hijab-muslim-stepmom-get-fucked-hard-so-hot-and-creampie-in-hotel-room-xhPwFEX" 2>/dev/null || echo "")

          echo "#EXTM3U" > mlf.m3u
          echo "" >> mlf.m3u

          if [ -n "$URL1" ]; then
            echo "#EXTINF:-1 tvg-id=\"mlf1\" tvg-name=\"mlf1\" group-title=\"MLF\",mlf1" >> mlf.m3u
            echo "$URL1" >> mlf.m3u
          else
            echo "#EXTINF:-1 tvg-id=\"mlf1\" tvg-name=\"mlf1\" group-title=\"MLF\",mlf1" >> mlf.m3u
            echo "https://example.com/stream.m3u8" >> mlf.m3u
          fi

          cat mlf.m3u

      - name: Commit playlist
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

          git add mlf.m3u
          git diff --cached --quiet || git commit -m "update mlf playlist"
          git push
