name: Auto Update Playlist

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-playlist:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Pull latest repo
        run: |
          git pull origin main

      - name: Download playlist
        run: |
          curl -L "https://raw.githubusercontent.com/hnnyo/cct/refs/heads/main/aku.m3u" -o tvok.m3u

      - name: Commit and Push if changed
        run: |
          git config --global user.name "playlist-bot"
          git config --global user.email "bot@github.com"

          git add tvok.m3u

          if git diff --cached --quiet; then
            echo "No changes detected"
          else
            git commit -m "Auto update playlist"
            git pull --rebase origin main
            git push origin main
          fi
