name: Auto Update Playlist

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: playlist-update
  cancel-in-progress: true

jobs:
  update:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0

      - name: Download playlist
        run: curl -L https://raw.githubusercontent.com/hnnyo/cct/main/aku.m3u -o tvok

      - name: Commit update
        run: |
          git config --global user.name "playlist-bot"
          git config --global user.email "bot@github.com"

          git add tvok

          if git diff --cached --quiet; then
            echo "No changes"
          else
            git commit -m "Auto update playlist"
            git pull --rebase origin main
            git push
          fi
