name: Auto Update Playlist

on:
schedule:
- cron: "0 * * * *"   # setiap 1 jam
workflow_dispatch:

permissions:
contents: write

jobs:
update:
runs-on: ubuntu-latest

steps:
  - name: Checkout repo
    uses: actions/checkout@v4
    with:
      fetch-depth: 0

  - name: Download new playlist
    run: |
      curl -L https://raw.githubusercontent.com/hnnyo/cct/main/aku.m3u -o tvok

  - name: Compare playlist
    id: compare
    run: |
      if [ -f tvok ]; then
        if cmp -s new_tvok tvok; then
          echo "same=true" >> $GITHUB_OUTPUT
        else
          echo "same=false" >> $GITHUB_OUTPUT
        fi
      else
        echo "same=false" >> $GITHUB_OUTPUT
      fi

  - name: Update file
    if: steps.compare.outputs.same == 'false'
    run: |
      mv new_tvok tvok

  - name: Commit update
    if: steps.compare.outputs.same == 'false'
    run: |
      git config --global user.name "playlist-bot"
      git config --global user.email "bot@github.com"

      git add tvok
      git commit -m "Update playlist"
      git push

  - name: No update
    if: steps.compare.outputs.same == 'true'
    run: echo "Playlist unchanged"
